apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: kube-workshop
  name: kube-workshop
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      labels:
        name: kube-workshop
    spec:
      containers:
      - name: kube-workshop
        image: rrequero/kube-workshop:1.0.7
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "256Mi"
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: prod
          - name: PASSWORD
            valueFrom:
                secretKeyRef:
                  name: kube-workshop-secrets
                  key: PASSWORD
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
      restartPolicy: Always
